imports:
  - http://cloudify.co/spec/fabric-plugin/1.5/plugin.yaml
  - http://www.getcloudify.org/spec/utilities-plugin/1.4.2.1/plugin.yaml

inputs:

  bootstrap:
    description: >
      If you are not using a pre-baked image, this is true.
    type: boolean
    default: False

  cli_package_url:
    description: >
      If inputs.bootstrap is false, this is the CLI RPM to install and bootstrap with.
    default: http://repository.cloudifysource.org/cloudify/4.2.0/ga-release/cloudify-cli-4.2ga.rpm

  create_secrets:
    description: >
      Whether to create the suggested secrets on the manager.
    default: true

  upload_plugins:
    description: >
      Whether to upload plugins to the manager.
    default: true

  plugin_urls:
    description: >
      Plugins used in AWS blueprint examples.
    default:
    - http://repository.cloudifysource.org/cloudify/wagons/cloudify-fabric-plugin/1.5/cloudify_fabric_plugin-1.5-py27-none-linux_x86_64-centos-Core.wgn
    - http://repository.cloudifysource.org/cloudify/wagons/cloudify-diamond-plugin/1.3.5/cloudify_diamond_plugin-1.3.5-py27-none-linux_x86_64-centos-Core.wgn
    - http://repository.cloudifysource.org/cloudify/wagons/cloudify-diamond-plugin/1.3.5/cloudify_diamond_plugin-1.3.5-py27-none-linux_x86_64-Ubuntu-trusty.wgn
    - https://github.com/cloudify-incubator/cloudify-kubernetes-plugin/releases/download/2.0.0/cloudify_kubernetes_plugin-2.0.0-py27-none-linux_x86_64-centos-Core.wgn
    - http://repository.cloudifysource.org/cloudify/wagons/cloudify-utilities-plugin/1.4.2.1/cloudify_utilities_plugin-1.4.2.1-py27-none-linux_x86_64-centos-Core.wgn
    - https://s3-eu-west-1.amazonaws.com/cloudify-release-eu/cloudify/wagons/cloudify-openstack-plugin/2.3.0/cloudify_openstack_plugin-2.3.0-py27-none-linux_x86_64-centos-Core.wgn
    - https://github.com/cloudify-cosmo/cloudify-openstack-plugin/releases/download/2.5.2/cloudify_openstack_plugin-2.5.2-py27-none-linux_x86_64-centos-Core.wgn
    - https://github.com/cloudify-cosmo/cloudify-aws-plugin/releases/download/1.5.1.2/cloudify_aws_plugin-1.5.1.2-py27-none-linux_x86_64-centos-Core.wgn
    - http://repository.cloudifysource.org/cloudify/wagons/cloudify-awssdk-plugin/1.2.0.1/cloudify_awssdk_plugin-1.2.0.1-py27-none-linux_x86_64-centos-Core.wgn
    - https://github.com/cloudify-incubator/cloudify-azure-plugin/releases/download/1.4.3/cloudify_azure_plugin-1.4.3-py27-none-linux_x86_64-centos-Core.wgn
    - http://repository.cloudifysource.org/cloudify/wagons/cloudify-gcp-plugin/1.3.0.1/cloudify_gcp_plugin-1.3.0.1-py27-none-linux_x86_64-centos-Core.wgn

node_types:

  cloudify.nodes.Manager.EnvironmentSetup:
    derived_from: cloudify.nodes.Root
    properties:
      bootstrap:
        default: { get_input: bootstrap }
      create_secrets:
        default: { get_input: create_secrets }
      upload_plugins:
        default: { get_input: upload_plugins }
    interfaces:
      cloudify.interfaces.lifecycle:
        create:
          implementation: fabric.fabric_plugin.tasks.run_task
          inputs:
            tasks_file:
              default: scripts/manager/create.py
            task_name:
              default: create
            task_properties:
              default: { get_input: create_inputs }
            fabric_env:
              default:
                host_string: { get_input: manager_ip }
                user: { get_input: cloudify_image_username }
                key_filename: { get_input: cloudify_key_file  }
        configure:
          implementation: scripts/manager/configure.py
          executor: central_deployment_agent
          inputs:
            manager_ip:
              default: { get_input: manager_ip }
            plugin_urls:
              default: { get_input: plugin_urls }
            secrets:
              default: { get_input: secrets }
        start:
          implementation: scripts/manager/start.py
          executor: central_deployment_agent
          inputs:
            manager_ip:
              default: { get_input: manager_ip }
            plugin_urls:
              default: { get_input: plugin_urls }
            secrets:
              default: { get_input: secrets }
        delete:
          implementation: scripts/manager/delete.py
          executor: central_deployment_agent

node_templates:

  ManagerSetup:
    type: cloudify.nodes.Manager.EnvironmentSetup
    relationships:
      - type: cloudify.relationships.depends_on
        target: cloudify_host
